### ISSUE TITLE
Remove all <br> tags

### ISSUE THREAD

**Issue by kyrose** [courtneypure/courtneypure.github.io#6]
I recommend that you remove all your `<br>` tags from [index.html](https://github.com/courtneypure/courtneypure.github.io/blob/master/index.html) and instead use CSS to space elements. It will make your code easier to read and debug!

I forgot where exactly I read that using `<br>` tags to add space is no longer considered good practice, and that using CSS for that purpose is preferred, but if I find it, I'll add it in a comment!

**Comment by courtneypure** [comment]
Thank you!  I think it's about time I start looking at those books I see floating around about clean code.  I had a lot of the `<br>` tags when I was using floats and just never thought about taking them out.  My work around for floats was not ideal!
